filter:
    excluded_paths: [tests/*]

checks:
    php:
        fix_use_statements:
            preserve_blanklines: true
            order_alphabetically: true

tools:
    external_code_coverage:
        timeout: 600
        runs: 3
